tap "supabase/tap"
tap "theboredteam/boring-notch", "https://github.com/TheBoredTeam/homebrew-boring-notch"
# Simple, modern, secure file encryption
brew "age"
# Dependency manager for Cocoa projects
brew "cocoapods"
# Fast and simple Node.js version manager
brew "fnm"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Fast, disk space efficient package manager
brew "pnpm"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Editor of encrypted files
brew "sops"
# Cross-shell prompt for astronauts
brew "starship"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Port of OpenAI's Whisper model in C/C++
brew "whisper.cpp"
# Supabase CLI
brew "supabase/tap/supabase", trusted: true
# Application uninstaller
cask "appcleaner"
cask "boring-notch", trusted: true
# Anthropic's official Claude AI desktop app
cask "claude"
# Window peeking utility app
cask "dockdoor"
# UI toolkit for building applications for mobile, web and desktop
cask "flutter"
cask "font-hack-nerd-font"
# GIT client
cask "fork"
# Web browser
cask "google-chrome"
# JetBrains tools manager
cask "jetbrains-toolbox"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Replacement for Docker Desktop
cask "orbstack"
# App wrapper for Postgres
cask "postgres-app"
# Music streaming service
cask "spotify"
# Open-source code editor
cask "visual-studio-code"
# Rust-based terminal
cask "warp"
# Video communication and virtual meeting platform
cask "zoom"
vscode "aaron-bond.better-comments"
vscode "anthropic.claude-code"
vscode "austenc.tailwind-docs"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.npm-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "fosshaas.fontsize-shortcuts"
vscode "github.github-vscode-theme"
vscode "heybourn.headwind"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "naumovs.color-highlight"
vscode "stivo.tailwind-fold"
vscode "styled-components.vscode-styled-components"
vscode "tombonnike.vscode-status-bar-format-toggle"
vscode "unifiedjs.vscode-mdx"
vscode "wayou.vscode-todo-highlight"
vscode "xabikos.javascriptsnippets"
vscode "yoavbls.pretty-ts-errors"
npm "@playwright/cli"
